### ISSUE TITLE
Only software I2C works

### ISSUE THREAD

**Issue by spleenware** [JJJS777/Hello_World_RadioLib_Heltec-V3_SX1262#2]
Have been tinkering with these newer V3 Heltecs, and trying to master the OLED.
I noticed only the U8G2 constructor for the SOFTWARE I2C works, Not hardware I2C. And it's super slow, of course :-(
Do you know what the issue is with the hardware I2C on this board?

**Comment by JJJS777** [comment]
Hi @spleenware, this is the U8G2 constructor using the hw i2c ```U8G2_SSD1306_128X64_NONAME_1_HW_I2C u8g2(U8G2_R0, oled_rst, oled_scl, oled_sda);```

rst, scl and sda pins are in a different order than with the U8G2 constructor using sw i2c.
Hope that works for u (::

**Comment by spleenware** [comment]
Yes, I noticed the param order difference. But doesn't work. Just blank screen.
The  _1_  for only partial frame buffer, is that the only way it will work? (Instead of _F_ for full frame buffer)

**Comment by JJJS777** [comment]
just tried it with full frame buffer (_F_ instead of _1_) and it worked for me

**Comment by spleenware** [comment]
AH, found the problem. I had the extra line at start of setup()
Wire.begin(17, 18);

Removed, and now works.
